fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    registry: 'git://github.com/puppetlabs/puppetlabs-registry.git'
    translate: 'https://github.com/puppetlabs/puppetlabs-translate'
  symlinks:
    "motd": "#{source_dir}"
