fixtures:
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    provision: 'git://github.com/puppetlabs/provision.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    registry: 'git://github.com/puppetlabs/puppetlabs-registry.git'
    translate: 'git://github.com/puppetlabs/puppetlabs-translate.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    motd: "#{source_dir}"
