fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    registry:
      repo: 'https://github.com/puppetlabs/puppetlabs-registry.git'
      ref: '1.1.0'
  symlinks:
    "motd": "#{source_dir}"
