---
common:
  service_url: https://facade-main-6f3kfepqcq-ew.a.run.app/v1/provision

".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
.rubocop.yml:
  include_todos: true

spec/default_facts.yml:
  extra_facts:
    networking:
      fqdn: "foo.example.com"
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/ci.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
