---
common:
  service_url: https://facade-main-6f3kfepqcq-ew.a.run.app/v1/provision

".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true

Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
    - gem: puppet_litmus
      git: https://github.com/puppetlabs/puppet_litmus
      ref: main
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.5.0')
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
  exclude_platforms:
    - Debian-11
    - RedHat-8
.github/workflows/pr_test.yml:
  unmanaged: false
  exclude_platforms:
    - Debian-11
    - RedHat-8
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
