---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - rm -rf /home/travis/.rvm
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec $CHECK'
bundler_args: --without system_tests
matrix:
  fast_finish: true
  include:
    - env: CHECK="pdk test unit"
branches:
  only:
    - master
    - /^v\d/
    - release
notifications:
  email: false
