name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@CAT-2286-Remove_puppet_7_test_infrastructure"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@CAT-2286-Remove_puppet_7_test_infrastructure"
    secrets: "inherit"
    with:
      runs_on: "ubuntu-20.04"
