name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    secrets: "inherit"

  Acceptance:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@maint-add_matrix_input"
    secrets: "inherit"
