name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@CAT-2451-Address_wrong_facter_versioning"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@CAT-2451-Address_wrong_facter_versioning"
    # test different PR, attempt to address facter issues
    secrets: "inherit"
    with:
      flags: "--nightly"
