name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 7
        stale-issue-message: 'Hi, this issue has been open for a while and has had no recent activity so it has been labeled for attention. With significant change within our team over the past 6 months, we are no longer aware if your issue is still relevant and/or up-to-date.\n\nIf this issue is still important and relevant to you, please drop a comment below and we will add this back to our community workload for prioritisation. Otherwise, it will be considered inactive and will be closed after 7 days. Closed issues can still be reopened if you comment on them shortly after it has been closed.'
        stale-issue-label: 'attention'
        stale-pr-message: 'Hi, this PR has been open for a while and has had no recent activity so it has been labeled for attention. With significant change within our team over the past 6 months, we are no longer aware if your PR is still relevant and/or up-to-date.\n\nIf this PR is still important and relevant to you, please drop a comment below and we will add this back to our community workload for prioritisation. Otherwise, it will be considered inactive and will be closed after 7 days. Closed PRs can still be reopened if you comment on them shortly after it has been closed.'
        stale-pr-label: 'needs-attention'
